<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-5KMFOFH9" failures="1" tests="1" name="Test(failed)" time="5.084" errors="0" timestamp="2025-03-18T21:10:30 IST">
  <testcase classname="com.TestNG.BasicScenario.TestDemo3_timeouts" name="testcase2" time="5.031">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.TestNG.BasicScenario.TestDemo3_timeouts.testcase2() didn&amp;apos;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.TestNG.BasicScenario.TestDemo3_timeouts.testcase2() didn't finish within the time-out 5000
at java.base@17.0.2/java.lang.Thread.sleep(Native Method)
at app//com.TestNG.BasicScenario.TestDemo3_timeouts.testcase2(TestDemo3_timeouts.java:24)
at java.base@17.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase classname="com.TestNG.BasicScenario.TestDemo3_timeouts" name="testcase1" time="0.0">
    <ignored/>
  </testcase> <!-- testcase1 -->
</testsuite> <!-- Test(failed) -->
